language: node_js

node_js:
  - '8'

env:
  global:
    - GH_REF: github.com/chun-wang/chun-wang.github.io.git

git:
  submodules: true

before_install:
  - git config --global user.name 'Charles Wang'
  - git config --global user.email 454774088@qq.com

install:
  - mv _config_maupassant.yml themes/maupassant/_config.yml
  - cp CNAME public/CNAME
  - npm install hexo-cli -g

script:
  - npm install
  - hexo generate
  - cd public
  - git init
  - git add --all
  - git commit -m "Update docs"
  - git push -f "https://${GH_Token}@${GH_REF}" master:master &> build.log
