fancybox: true
disqus: ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b

gitment:
  enable: true
  owner: chun-wang
  repo: chun-wang.github.io
  client_id: cedb5d41fdb586b27010
  client_secret: 64eccb5103d95e498074fb6c263f60549842bafa
gitalk:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner:  ## Your GitHub ID, e.g. username
  repo:  ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id:  ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret:  ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin:  ## Github repo owner and collaborators, only these guys can initialize github issues.
valine: ## https://valine.js.org
  enable: false ## If you want to use Valine comment system, please set the value to true.
  appid: ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: Just so so ## Comment box placeholders.
  avatar: 'mm' ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.


google_search: false 
baidu_search: true 
swiftype: 
tinysou: 
self_search: false 
google_analytics: 
baidu_analytics: 
show_category_count: true
toc_number: true 
shareto: false 
busuanzi: false 
wordcount: true 
widgets_on_small_screens: false 
canvas_nest:
  enable: false 
  color: 
  opacity: 
  zIndex: 
  count: 
donate:
  enable: false 
  github: 
  alipay_qr: 
  wechat_qr: 
  btc_qr: 
  btc_key: 
  paypal_url: 
post_copyright:
  enable: true 
  author: chunwang
  copyright_text: The author owns the copyright, please indicate the source reproduced.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: history
    directory: timeline/
    icon: fa-history
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: 
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: Github
    url: https://github.com/chun-wang

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2018/06/28-切换主题到maupassant
  - num: 3
    word: 2018/10/09-开启我的macbook写作之旅

# Static files
js: js
css: css

# Theme version
version: 0.0.1